# permissions to do viewer bgps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgp-viewer-role
rules:
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - bgps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - bgps/status
  verbs:
  - get
