# permissions to do edit devices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: device-editor-role
rules:
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - devices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - devices/status
  verbs:
  - get
  - patch
  - update
