# permissions to do viewer devices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: device-viewer-role
rules:
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - devices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - devices/status
  verbs:
  - get
