# permissions to do viewer interfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: interface-viewer-role
rules:
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - interfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - interfaces/status
  verbs:
  - get
