
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - bgps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - bgps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - interfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devicemanager.juniper.net
  resources:
  - interfaces/status
  verbs:
  - get
  - patch
  - update
