// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResult) Reset()         { *m = CreateResult{} }
func (m *CreateResult) String() string { return proto.CompactTextString(m) }
func (*CreateResult) ProtoMessage()    {}
func (*CreateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{0}
}

func (m *CreateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResult.Unmarshal(m, b)
}
func (m *CreateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResult.Marshal(b, m, deterministic)
}
func (m *CreateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResult.Merge(m, src)
}
func (m *CreateResult) XXX_Size() int {
	return xxx_messageInfo_CreateResult.Size(m)
}
func (m *CreateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResult proto.InternalMessageInfo

func (m *CreateResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type UpdateResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResult) Reset()         { *m = UpdateResult{} }
func (m *UpdateResult) String() string { return proto.CompactTextString(m) }
func (*UpdateResult) ProtoMessage()    {}
func (*UpdateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{1}
}

func (m *UpdateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResult.Unmarshal(m, b)
}
func (m *UpdateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResult.Marshal(b, m, deterministic)
}
func (m *UpdateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResult.Merge(m, src)
}
func (m *UpdateResult) XXX_Size() int {
	return xxx_messageInfo_UpdateResult.Size(m)
}
func (m *UpdateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResult.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResult proto.InternalMessageInfo

func (m *UpdateResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type DeleteResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResult) Reset()         { *m = DeleteResult{} }
func (m *DeleteResult) String() string { return proto.CompactTextString(m) }
func (*DeleteResult) ProtoMessage()    {}
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{2}
}

func (m *DeleteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResult.Unmarshal(m, b)
}
func (m *DeleteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResult.Marshal(b, m, deterministic)
}
func (m *DeleteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResult.Merge(m, src)
}
func (m *DeleteResult) XXX_Size() int {
	return xxx_messageInfo_DeleteResult.Size(m)
}
func (m *DeleteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResult proto.InternalMessageInfo

func (m *DeleteResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type ReadResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResult) Reset()         { *m = ReadResult{} }
func (m *ReadResult) String() string { return proto.CompactTextString(m) }
func (*ReadResult) ProtoMessage()    {}
func (*ReadResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{3}
}

func (m *ReadResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResult.Unmarshal(m, b)
}
func (m *ReadResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResult.Marshal(b, m, deterministic)
}
func (m *ReadResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResult.Merge(m, src)
}
func (m *ReadResult) XXX_Size() int {
	return xxx_messageInfo_ReadResult.Size(m)
}
func (m *ReadResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResult proto.InternalMessageInfo

func (m *ReadResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type Intf struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	InterfaceIdentifier  string   `protobuf:"bytes,2,opt,name=InterfaceIdentifier,proto3" json:"InterfaceIdentifier,omitempty"`
	Units                []*Unit  `protobuf:"bytes,3,rep,name=Units,proto3" json:"Units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Intf) Reset()         { *m = Intf{} }
func (m *Intf) String() string { return proto.CompactTextString(m) }
func (*Intf) ProtoMessage()    {}
func (*Intf) Descriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{4}
}

func (m *Intf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Intf.Unmarshal(m, b)
}
func (m *Intf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Intf.Marshal(b, m, deterministic)
}
func (m *Intf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Intf.Merge(m, src)
}
func (m *Intf) XXX_Size() int {
	return xxx_messageInfo_Intf.Size(m)
}
func (m *Intf) XXX_DiscardUnknown() {
	xxx_messageInfo_Intf.DiscardUnknown(m)
}

var xxx_messageInfo_Intf proto.InternalMessageInfo

func (m *Intf) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Intf) GetInterfaceIdentifier() string {
	if m != nil {
		return m.InterfaceIdentifier
	}
	return ""
}

func (m *Intf) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

type DeviceInterfaceStatus struct {
	InterfaceReference   *InterfaceRef `protobuf:"bytes,1,opt,name=InterfaceReference,proto3" json:"InterfaceReference,omitempty"`
	CommitStatus         string        `protobuf:"bytes,2,opt,name=CommitStatus,proto3" json:"CommitStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeviceInterfaceStatus) Reset()         { *m = DeviceInterfaceStatus{} }
func (m *DeviceInterfaceStatus) String() string { return proto.CompactTextString(m) }
func (*DeviceInterfaceStatus) ProtoMessage()    {}
func (*DeviceInterfaceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{5}
}

func (m *DeviceInterfaceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInterfaceStatus.Unmarshal(m, b)
}
func (m *DeviceInterfaceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInterfaceStatus.Marshal(b, m, deterministic)
}
func (m *DeviceInterfaceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInterfaceStatus.Merge(m, src)
}
func (m *DeviceInterfaceStatus) XXX_Size() int {
	return xxx_messageInfo_DeviceInterfaceStatus.Size(m)
}
func (m *DeviceInterfaceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInterfaceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInterfaceStatus proto.InternalMessageInfo

func (m *DeviceInterfaceStatus) GetInterfaceReference() *InterfaceRef {
	if m != nil {
		return m.InterfaceReference
	}
	return nil
}

func (m *DeviceInterfaceStatus) GetCommitStatus() string {
	if m != nil {
		return m.CommitStatus
	}
	return ""
}

type InterfaceRef struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	InterfaceIdentifier  string   `protobuf:"bytes,3,opt,name=InterfaceIdentifier,proto3" json:"InterfaceIdentifier,omitempty"`
	UID                  string   `protobuf:"bytes,4,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceRef) Reset()         { *m = InterfaceRef{} }
func (m *InterfaceRef) String() string { return proto.CompactTextString(m) }
func (*InterfaceRef) ProtoMessage()    {}
func (*InterfaceRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{6}
}

func (m *InterfaceRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceRef.Unmarshal(m, b)
}
func (m *InterfaceRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceRef.Marshal(b, m, deterministic)
}
func (m *InterfaceRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceRef.Merge(m, src)
}
func (m *InterfaceRef) XXX_Size() int {
	return xxx_messageInfo_InterfaceRef.Size(m)
}
func (m *InterfaceRef) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceRef.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceRef proto.InternalMessageInfo

func (m *InterfaceRef) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InterfaceRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InterfaceRef) GetInterfaceIdentifier() string {
	if m != nil {
		return m.InterfaceIdentifier
	}
	return ""
}

func (m *InterfaceRef) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

type Unit struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Addresses            []string `protobuf:"bytes,2,rep,name=Addresses,proto3" json:"Addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unit) Reset()         { *m = Unit{} }
func (m *Unit) String() string { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()    {}
func (*Unit) Descriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{7}
}

func (m *Unit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unit.Unmarshal(m, b)
}
func (m *Unit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unit.Marshal(b, m, deterministic)
}
func (m *Unit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unit.Merge(m, src)
}
func (m *Unit) XXX_Size() int {
	return xxx_messageInfo_Unit.Size(m)
}
func (m *Unit) XXX_DiscardUnknown() {
	xxx_messageInfo_Unit.DiscardUnknown(m)
}

var xxx_messageInfo_Unit proto.InternalMessageInfo

func (m *Unit) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Unit) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateResult)(nil), "protos.CreateResult")
	proto.RegisterType((*UpdateResult)(nil), "protos.UpdateResult")
	proto.RegisterType((*DeleteResult)(nil), "protos.DeleteResult")
	proto.RegisterType((*ReadResult)(nil), "protos.ReadResult")
	proto.RegisterType((*Intf)(nil), "protos.Intf")
	proto.RegisterType((*DeviceInterfaceStatus)(nil), "protos.DeviceInterfaceStatus")
	proto.RegisterType((*InterfaceRef)(nil), "protos.InterfaceRef")
	proto.RegisterType((*Unit)(nil), "protos.Unit")
}

func init() { proto.RegisterFile("device.proto", fileDescriptor_870276a56ac00da5) }

var fileDescriptor_870276a56ac00da5 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcb, 0x6a, 0xf3, 0x30,
	0x10, 0x85, 0xe3, 0x4b, 0xc2, 0x9f, 0x89, 0xf9, 0x29, 0xd3, 0x0b, 0xa6, 0x74, 0x11, 0x44, 0x29,
	0xa1, 0x8b, 0x50, 0xd2, 0xbe, 0x40, 0x89, 0x37, 0xde, 0x74, 0xa1, 0x92, 0x07, 0x70, 0xed, 0x31,
	0x18, 0x12, 0xc7, 0x48, 0x4a, 0xf7, 0x85, 0xbe, 0x5b, 0x5f, 0xab, 0x48, 0x4a, 0x14, 0xb5, 0x24,
	0xa4, 0x2b, 0x8f, 0x66, 0x3e, 0x8f, 0x8f, 0x0f, 0x47, 0x90, 0x54, 0xf4, 0xde, 0x94, 0x34, 0xed,
	0xc4, 0x5a, 0xad, 0x71, 0x60, 0x1e, 0x92, 0xdd, 0x41, 0x32, 0x17, 0x54, 0x28, 0xe2, 0x24, 0x37,
	0x4b, 0x85, 0x57, 0x30, 0x10, 0xa6, 0x4a, 0x83, 0x71, 0x30, 0xf9, 0xc7, 0xb7, 0x27, 0xcd, 0x2d,
	0xba, 0xea, 0x4f, 0x5c, 0x46, 0x4b, 0x3a, 0xc9, 0xdd, 0x02, 0x70, 0x2a, 0xaa, 0x13, 0x54, 0x07,
	0x71, 0xde, 0xaa, 0x1a, 0x11, 0xe2, 0x97, 0x62, 0x45, 0x66, 0x3a, 0xe4, 0xa6, 0xc6, 0x07, 0x38,
	0xcf, 0x5b, 0x45, 0xa2, 0x2e, 0x4a, 0xca, 0x2b, 0x6a, 0x55, 0x53, 0x37, 0x24, 0xd2, 0xd0, 0x20,
	0x87, 0x46, 0xc8, 0xa0, 0xbf, 0x68, 0x1b, 0x25, 0xd3, 0x68, 0x1c, 0x4d, 0x46, 0xb3, 0xc4, 0x5a,
	0x21, 0xa7, 0xba, 0xc9, 0xed, 0x88, 0x7d, 0x04, 0x70, 0x99, 0x19, 0xa3, 0xdc, 0x86, 0x57, 0x55,
	0xa8, 0x8d, 0xc4, 0x0c, 0xd0, 0xb5, 0x38, 0xd5, 0x24, 0xa8, 0x2d, 0xad, 0xa2, 0xd1, 0xec, 0x62,
	0xb7, 0xca, 0x27, 0xf8, 0x01, 0x1e, 0x19, 0x24, 0xf3, 0xf5, 0x6a, 0xd5, 0x28, 0xbb, 0x75, 0x2b,
	0xf7, 0x47, 0x8f, 0x7d, 0x06, 0x90, 0xf8, 0xaf, 0xe2, 0x0d, 0x0c, 0xf5, 0x2f, 0xcb, 0xae, 0x28,
	0x77, 0x1e, 0xec, 0x1b, 0xce, 0x9c, 0xf0, 0xb4, 0x39, 0xd1, 0x71, 0x73, 0xce, 0x20, 0x5a, 0xe4,
	0x59, 0x1a, 0x1b, 0x42, 0x97, 0xec, 0x09, 0x62, 0xed, 0x09, 0xfe, 0x87, 0x30, 0xcf, 0xcc, 0x67,
	0xfb, 0x3c, 0xcc, 0x33, 0xad, 0xe6, 0xb9, 0xaa, 0x04, 0x49, 0x49, 0x5a, 0x7f, 0xa4, 0xd5, 0xb8,
	0xc6, 0xec, 0x2b, 0x80, 0xa1, 0xdb, 0x8f, 0x53, 0x18, 0xd8, 0x78, 0x61, 0xe2, 0x59, 0x54, 0x5f,
	0x3b, 0xc3, 0xfc, 0xf0, 0xb1, 0x9e, 0xe6, 0x6d, 0xcc, 0x8e, 0xf1, 0x7e, 0x08, 0x2d, 0x6f, 0xe3,
	0x76, 0x8c, 0xf7, 0xc3, 0xc8, 0x7a, 0x78, 0x0f, 0xb1, 0x8e, 0xdd, 0x2f, 0x1a, 0x77, 0xa7, 0x7d,
	0x24, 0x59, 0xef, 0xcd, 0x5e, 0x91, 0xc7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0x25, 0x99,
	0xe0, 0x39, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InterfaceClient is the client API for Interface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InterfaceClient interface {
	Create(ctx context.Context, in *Intf, opts ...grpc.CallOption) (*CreateResult, error)
	Update(ctx context.Context, in *Intf, opts ...grpc.CallOption) (*UpdateResult, error)
	Delete(ctx context.Context, in *Intf, opts ...grpc.CallOption) (*DeleteResult, error)
	Read(ctx context.Context, in *Intf, opts ...grpc.CallOption) (*ReadResult, error)
}

type interfaceClient struct {
	cc *grpc.ClientConn
}

func NewInterfaceClient(cc *grpc.ClientConn) InterfaceClient {
	return &interfaceClient{cc}
}

func (c *interfaceClient) Create(ctx context.Context, in *Intf, opts ...grpc.CallOption) (*CreateResult, error) {
	out := new(CreateResult)
	err := c.cc.Invoke(ctx, "/protos.Interface/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interfaceClient) Update(ctx context.Context, in *Intf, opts ...grpc.CallOption) (*UpdateResult, error) {
	out := new(UpdateResult)
	err := c.cc.Invoke(ctx, "/protos.Interface/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interfaceClient) Delete(ctx context.Context, in *Intf, opts ...grpc.CallOption) (*DeleteResult, error) {
	out := new(DeleteResult)
	err := c.cc.Invoke(ctx, "/protos.Interface/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interfaceClient) Read(ctx context.Context, in *Intf, opts ...grpc.CallOption) (*ReadResult, error) {
	out := new(ReadResult)
	err := c.cc.Invoke(ctx, "/protos.Interface/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterfaceServer is the server API for Interface service.
type InterfaceServer interface {
	Create(context.Context, *Intf) (*CreateResult, error)
	Update(context.Context, *Intf) (*UpdateResult, error)
	Delete(context.Context, *Intf) (*DeleteResult, error)
	Read(context.Context, *Intf) (*ReadResult, error)
}

// UnimplementedInterfaceServer can be embedded to have forward compatible implementations.
type UnimplementedInterfaceServer struct {
}

func (*UnimplementedInterfaceServer) Create(ctx context.Context, req *Intf) (*CreateResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedInterfaceServer) Update(ctx context.Context, req *Intf) (*UpdateResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedInterfaceServer) Delete(ctx context.Context, req *Intf) (*DeleteResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedInterfaceServer) Read(ctx context.Context, req *Intf) (*ReadResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}

func RegisterInterfaceServer(s *grpc.Server, srv InterfaceServer) {
	s.RegisterService(&_Interface_serviceDesc, srv)
}

func _Interface_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Intf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Interface/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceServer).Create(ctx, req.(*Intf))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interface_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Intf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Interface/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceServer).Update(ctx, req.(*Intf))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interface_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Intf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Interface/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceServer).Delete(ctx, req.(*Intf))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interface_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Intf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Interface/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceServer).Read(ctx, req.(*Intf))
	}
	return interceptor(ctx, in, info, handler)
}

var _Interface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Interface",
	HandlerType: (*InterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Interface_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Interface_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Interface_Delete_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Interface_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device.proto",
}
