---
apiVersion: devicemanager.juniper.net/v1
kind: Interface
metadata:
  name: eth0-group2
  labels:
    group: group2
spec:
  interfaceIdentifier: eth0
  units:
  - id: 0
    addresses:
    - 1.1.1.1/24
    - 1::1/64
  - id: 1
    addresses:
    - 2.1.1.1/24
    - 2::1/64
